# https://gitpod.io/#https://github.com/CaravanaCloud/rinhadebackend
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Init
    init: |
      mvn clean install
      mkdir -p "$HOME/projects/"
      ln -sf "/workspace/rinha-de-backend-2023-q3" "$HOME/projects/rinha-de-backend-2023-q3"
      echo "done init rinha"
    command: echo "welcome to the rinha"

additionalRepositories:
    - url: https://github.com/zanfranceschi/rinha-de-backend-2023-q3
      checkoutLocation: rinha-de-backend-2023-q3

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
    - redhat.fabric8-analytics
    - ms-azuretools.vscode-docker
    - github.vscode-github-actions


ports:
  - port: 3306
    onOpen: ignore
  - port: 5000
    onOpen: ignore
    visibility: public
  - port: 5432
    onOpen: ignore
    visibility: public
  - port: 5500
    onOpen: ignore
    visibility: public
  - port: 8080
    onOpen: ignore
    visibility: public
  - port: 9090
    onOpen: ignore
    visibility: public
  - port: 9091
    onOpen: ignore
    visibility: public
  - port: 9092
    onOpen: ignore
    visibility: public
  - port: 9999
    onOpen: ignore
    visibility: public
