version: '3.5'
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
#    volumes:
#      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'
  
  api01:
    image: zanfranceschi/rinha-api-2023
    hostname: rinha-api01
    depends_on:
      - db
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc://postgresql://db/rinha
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=123
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.0GB'
  
#  api01:
#    image: zanfranceschi/rinha-api-2023
#    hostname: rinha-api01
#    depends_on:
#      - db
#    environment:
#      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:/mysql://db/rinha
#      - QUARKUS_DATASOURCE_DB_KIND=postgres
#      - QUARKUS_DATASOURCE_USERNAME=admin
#      - QUARKUS_DATASOURCE_PASSWORD=123
#    expose:
#      - "9090"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: '1.0GB'
  
#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - api01
#      - api02
#    ports:
#      - "9999:9999"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.25'
#          memory: '0.1GB'

networks:
  default:
    driver: bridge
    name: rinha