---
name: 0 Build every push

on:
  workflow_dispatch: { }
  push:
    branches:
      - "**"

jobs:
  build:
    name: TDC Build
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ENV_ID: beta

    steps:
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '20'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: checkout code
        uses: actions/checkout@v3

      - name: Build all modules
        run: mvn clean verify
